### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/perl6-Toaster#7]
See the screnshot:

![image](https://user-images.githubusercontent.com/5507503/41626938-e370d0d8-7426-11e8-8655-f63bcc616e06.png)

I think revisions are sorted alphabetically but the output of `git describe` can't be sorted like that.

**Comment by AlexDaniel** [comment]
FWIW same change has to be done in p5 viewer, but I don't know if it's maintained (I use it for some reason, don't know why).

**Comment by zoffixznet** [comment]
Ah right. I think P6's version leaks memory and is outdated and the P5 version is what's meant to be used.
